# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ca3158430c86e83efab2e7d37710f6ec731162886c218a18ac153d3c8de939b06b347e5ee7cc1e236e00c193e7f21a02f2dc24fb994a677dcf282eb912d6b9b

test:
  secret_key_base: adfb9252a078378af4d922c6b0e6d93f449155809a639223ceb0b3b23aac33525ba04663945ad2aebdfb5b67f71ec8c506ccf50534fdf52452e60221bc110d06

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
